height: 500
toolbar:
  - formatselect fontsizeselect styleselect alignleft aligncenter alignright | bold italic forecolor backcolor| undo redo | image media link | imagetools | emoticons | paste | print |
plugins:
  - link
  - wordcount
  - paste
  - image
  - media
  - code
  - codesample
  - imagetools
  - table
  - insertdatetime
  - charmap
  - print
  - preview
  - anchor
  - searchreplace
  - fullscreen
  - emoticons
language: es
relative_urls: true
browser_spellcheck:
  - true
images_upload_url: "/admin/upload"
automatic_uploads: false
file_picker_types: "file image media"
setup:
  function(ed) {
    ed.on('init', function() 
    {
        this.getDoc().body.style.fontSize = '12pt';
    });
  }