toolbar:
  - styleselect | fontselect fontsizeselect | alignleft aligncenter alignright | bold italic forecolor backcolor | undo redo | image media link | imagetools | emoticons | paste | print
plugins:
  - image
  - link
  - wordcount
  - paste
  - image
  - media
  - code
  - codesample
  - autoresize
  - imagetools
  - table
  - insertdatetime
  - charmap
  - print
  - preview
  - anchor
  - searchreplace
  - fullscreen
  - emoticons
  - textcolor
language:
  - es
browser_spellcheck:
  - true
