toolbar:
  - styleselect alignleft aligncenter alignright | bold italic forecolor backcolor| undo redo | image media link | imagetools | emoticons | paste | print |
plugins:
  - link
  - wordcount
  - paste
  - image
  - media
  - code
  - codesample
  - imagetools
  - table
  - insertdatetime
  - charmap
  - print
  - preview
  - anchor
  - searchreplace
  - fullscreen
  - emoticons
  - textcolor
  - theme_advanced_fonts
language:
  - es
theme_advanced_fonts : "Andale Mono=andale mono,times;"+
    "Arial=arial,helvetica,sans-serif;"+
    "Arial Black=arial black,avant garde;"+
    "Book Antiqua=book antiqua,palatino;"+
    "Comic Sans MS=comic sans ms,sans-serif;"+
    "Courier New=courier new,courier;"+
    "Georgia=georgia,palatino;"+
    "Helvetica=helvetica;"+
    "Impact=impact,chicago;"+
    "Symbol=symbol;"+
    "Tahoma=tahoma,arial,helvetica,sans-serif;"+
    "Terminal=terminal,monaco;"+
    "Times New Roman=times new roman,times;"+
    "Trebuchet MS=trebuchet ms,geneva;"+
    "Verdana=verdana,geneva;"+
    "Webdings=webdings;"+
    "Wingdings=wingdings,zapf dingbats"
relative_urls: false
browser_spellcheck:
  - true
images_upload_url: "/admin/upload"
automatic_uploads: false
file_picker_types: "file image media"
