id:  3,
title:  "Elon Musk y The Boring Company muestran su sistema de túneles en acción",
 slug:  "slug-6535",
content:  "<p>The Boring Company abri&oacute; su primera l&iacute;nea de transporte para que los mortales conozcamos el futuro del desplazamiento.</p>",
status:  "Publicado",
published_at:  Fri, 05 Apr 2019 17:15:00 -03 -03:00,
main_image_id:  1,
term_id:  nil,
post_parent_id:  nil,
visibility:  "Público",
post_class:  "tipo",
post_order:  nil,
created_at:  Thu, 04 Apr 2019 17:25:49 -03 -03:00,
updated_at:  Thu, 11 Apr 2019 12:22:43 -04 -04:00,
deleted_at:  nil,
user_id:  1,
post_type:  "Corporativas",
format:  0,
important:  true,
permission:  nil,
extract:  nil,
former_id:  nil,
migrated_id:  nil,
migrated_image_filename:  nil